# Book settings
title                       : Open Science Project
author                      : Kolunga
copyright                   : "2023"
logo                        :

# Execution settings
execute:
  execute_notebooks         : off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")